//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationListResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationSummaryView[] LoanApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationSummaryView[] LoanApplications {
            get {
                return this.LoanApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanApplicationsField, value) != true)) {
                    this.LoanApplicationsField = value;
                    this.RaisePropertyChanged("LoanApplications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationSummaryView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationSummaryView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasOffer {
            get {
                return this.HasOfferField;
            }
            set {
                if ((this.HasOfferField.Equals(value) != true)) {
                    this.HasOfferField = value;
                    this.RaisePropertyChanged("HasOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationGetByIdRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationGetByIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationGetByIdResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationGetByIdResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationDetailView LoanApplicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationDetailView LoanApplication {
            get {
                return this.LoanApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanApplicationField, value) != true)) {
                    this.LoanApplicationField = value;
                    this.RaisePropertyChanged("LoanApplication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationDetailView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationDetailView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView[] AssetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.BorrowerView[] BorrowersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView[] DebtsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView[] Assets {
            get {
                return this.AssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetsField, value) != true)) {
                    this.AssetsField = value;
                    this.RaisePropertyChanged("Assets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.BorrowerView[] Borrowers {
            get {
                return this.BorrowersField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowersField, value) != true)) {
                    this.BorrowersField = value;
                    this.RaisePropertyChanged("Borrowers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView[] Debts {
            get {
                return this.DebtsField;
            }
            set {
                if ((object.ReferenceEquals(this.DebtsField, value) != true)) {
                    this.DebtsField = value;
                    this.RaisePropertyChanged("Debts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasOffer {
            get {
                return this.HasOfferField;
            }
            set {
                if ((this.HasOfferField.Equals(value) != true)) {
                    this.HasOfferField = value;
                    this.RaisePropertyChanged("HasOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanTerm {
            get {
                return this.LoanTermField;
            }
            set {
                if ((this.LoanTermField.Equals(value) != true)) {
                    this.LoanTermField = value;
                    this.RaisePropertyChanged("LoanTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyCity {
            get {
                return this.PropertyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyCityField, value) != true)) {
                    this.PropertyCityField = value;
                    this.RaisePropertyChanged("PropertyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyPostCode {
            get {
                return this.PropertyPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyPostCodeField, value) != true)) {
                    this.PropertyPostCodeField = value;
                    this.RaisePropertyChanged("PropertyPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyStreet {
            get {
                return this.PropertyStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyStreetField, value) != true)) {
                    this.PropertyStreetField = value;
                    this.RaisePropertyChanged("PropertyStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyTown {
            get {
                return this.PropertyTownField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTownField, value) != true)) {
                    this.PropertyTownField = value;
                    this.RaisePropertyChanged("PropertyTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyValue {
            get {
                return this.PropertyValueField;
            }
            set {
                if ((this.PropertyValueField.Equals(value) != true)) {
                    this.PropertyValueField = value;
                    this.RaisePropertyChanged("PropertyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class AssetView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BorrowerView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class BorrowerView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankSortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditAgencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthlyIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber {
            get {
                return this.BankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNumberField, value) != true)) {
                    this.BankAccountNumberField = value;
                    this.RaisePropertyChanged("BankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountname {
            get {
                return this.BankAccountnameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountnameField, value) != true)) {
                    this.BankAccountnameField = value;
                    this.RaisePropertyChanged("BankAccountname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankSortCode {
            get {
                return this.BankSortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankSortCodeField, value) != true)) {
                    this.BankSortCodeField = value;
                    this.RaisePropertyChanged("BankSortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditAgency {
            get {
                return this.CreditAgencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditAgencyField, value) != true)) {
                    this.CreditAgencyField = value;
                    this.RaisePropertyChanged("CreditAgency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditScore {
            get {
                return this.CreditScoreField;
            }
            set {
                if ((this.CreditScoreField.Equals(value) != true)) {
                    this.CreditScoreField = value;
                    this.RaisePropertyChanged("CreditScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerCity {
            get {
                return this.EmployerCityField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerCityField, value) != true)) {
                    this.EmployerCityField = value;
                    this.RaisePropertyChanged("EmployerCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerName {
            get {
                return this.EmployerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerNameField, value) != true)) {
                    this.EmployerNameField = value;
                    this.RaisePropertyChanged("EmployerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerPostCode {
            get {
                return this.EmployerPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerPostCodeField, value) != true)) {
                    this.EmployerPostCodeField = value;
                    this.RaisePropertyChanged("EmployerPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerStreet {
            get {
                return this.EmployerStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerStreetField, value) != true)) {
                    this.EmployerStreetField = value;
                    this.RaisePropertyChanged("EmployerStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerTown {
            get {
                return this.EmployerTownField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerTownField, value) != true)) {
                    this.EmployerTownField = value;
                    this.RaisePropertyChanged("EmployerTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthlyIncome {
            get {
                return this.MonthlyIncomeField;
            }
            set {
                if ((this.MonthlyIncomeField.Equals(value) != true)) {
                    this.MonthlyIncomeField = value;
                    this.RaisePropertyChanged("MonthlyIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebtView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class DebtView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float BalanceOwedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MonthlyPaymentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float BalanceOwed {
            get {
                return this.BalanceOwedField;
            }
            set {
                if ((this.BalanceOwedField.Equals(value) != true)) {
                    this.BalanceOwedField = value;
                    this.RaisePropertyChanged("BalanceOwed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditorName {
            get {
                return this.CreditorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditorNameField, value) != true)) {
                    this.CreditorNameField = value;
                    this.RaisePropertyChanged("CreditorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MonthlyPayment {
            get {
                return this.MonthlyPaymentField;
            }
            set {
                if ((this.MonthlyPaymentField.Equals(value) != true)) {
                    this.MonthlyPaymentField = value;
                    this.RaisePropertyChanged("MonthlyPayment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationCreateRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationCreateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationCreateView LoanApplicationViewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationCreateView LoanApplicationView {
            get {
                return this.LoanApplicationViewField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanApplicationViewField, value) != true)) {
                    this.LoanApplicationViewField = value;
                    this.RaisePropertyChanged("LoanApplicationView");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationCreateView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationCreateView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView Asset1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView Asset2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView Asset3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.BorrowerView Borrower1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.BorrowerView Borrower2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView Debt1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView Debt2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView Debt3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSecondBorrowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView Asset1 {
            get {
                return this.Asset1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Asset1Field, value) != true)) {
                    this.Asset1Field = value;
                    this.RaisePropertyChanged("Asset1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView Asset2 {
            get {
                return this.Asset2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Asset2Field, value) != true)) {
                    this.Asset2Field = value;
                    this.RaisePropertyChanged("Asset2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.AssetView Asset3 {
            get {
                return this.Asset3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Asset3Field, value) != true)) {
                    this.Asset3Field = value;
                    this.RaisePropertyChanged("Asset3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.BorrowerView Borrower1 {
            get {
                return this.Borrower1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Borrower1Field, value) != true)) {
                    this.Borrower1Field = value;
                    this.RaisePropertyChanged("Borrower1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.BorrowerView Borrower2 {
            get {
                return this.Borrower2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Borrower2Field, value) != true)) {
                    this.Borrower2Field = value;
                    this.RaisePropertyChanged("Borrower2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView Debt1 {
            get {
                return this.Debt1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Debt1Field, value) != true)) {
                    this.Debt1Field = value;
                    this.RaisePropertyChanged("Debt1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView Debt2 {
            get {
                return this.Debt2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Debt2Field, value) != true)) {
                    this.Debt2Field = value;
                    this.RaisePropertyChanged("Debt2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.DebtView Debt3 {
            get {
                return this.Debt3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Debt3Field, value) != true)) {
                    this.Debt3Field = value;
                    this.RaisePropertyChanged("Debt3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasOffer {
            get {
                return this.HasOfferField;
            }
            set {
                if ((this.HasOfferField.Equals(value) != true)) {
                    this.HasOfferField = value;
                    this.RaisePropertyChanged("HasOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSecondBorrower {
            get {
                return this.HasSecondBorrowerField;
            }
            set {
                if ((this.HasSecondBorrowerField.Equals(value) != true)) {
                    this.HasSecondBorrowerField = value;
                    this.RaisePropertyChanged("HasSecondBorrower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanTerm {
            get {
                return this.LoanTermField;
            }
            set {
                if ((this.LoanTermField.Equals(value) != true)) {
                    this.LoanTermField = value;
                    this.RaisePropertyChanged("LoanTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyCity {
            get {
                return this.PropertyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyCityField, value) != true)) {
                    this.PropertyCityField = value;
                    this.RaisePropertyChanged("PropertyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyPostCode {
            get {
                return this.PropertyPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyPostCodeField, value) != true)) {
                    this.PropertyPostCodeField = value;
                    this.RaisePropertyChanged("PropertyPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyStreet {
            get {
                return this.PropertyStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyStreetField, value) != true)) {
                    this.PropertyStreetField = value;
                    this.RaisePropertyChanged("PropertyStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyTown {
            get {
                return this.PropertyTownField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTownField, value) != true)) {
                    this.PropertyTownField = value;
                    this.RaisePropertyChanged("PropertyTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyValue {
            get {
                return this.PropertyValueField;
            }
            set {
                if ((this.PropertyValueField.Equals(value) != true)) {
                    this.PropertyValueField = value;
                    this.RaisePropertyChanged("PropertyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanApplicationCreateResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class LoanApplicationCreateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanApplicationId {
            get {
                return this.LoanApplicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanApplicationIdField, value) != true)) {
                    this.LoanApplicationIdField = value;
                    this.RaisePropertyChanged("LoanApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferLetterGetByIdRequest", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class OfferLetterGetByIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferLetterGetByIdResponse", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Messa" +
        "ges")]
    [System.SerializableAttribute()]
    public partial class OfferLetterGetByIdResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.OfferLetterView OfferLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.OfferLetterView OfferLetter {
            get {
                return this.OfferLetterField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferLetterField, value) != true)) {
                    this.OfferLetterField = value;
                    this.RaisePropertyChanged("OfferLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferLetterView", Namespace="http://schemas.datacontract.org/2004/07/ProEnt.LoanPrequalification.Service.Views" +
        "")]
    [System.SerializableAttribute()]
    public partial class OfferLetterView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSecondBorrowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float InterestRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Recipient2CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Recipient2NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Recipient2PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Recipient2StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Recipient2TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientTownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSecondBorrower {
            get {
                return this.HasSecondBorrowerField;
            }
            set {
                if ((this.HasSecondBorrowerField.Equals(value) != true)) {
                    this.HasSecondBorrowerField = value;
                    this.RaisePropertyChanged("HasSecondBorrower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float InterestRate {
            get {
                return this.InterestRateField;
            }
            set {
                if ((this.InterestRateField.Equals(value) != true)) {
                    this.InterestRateField = value;
                    this.RaisePropertyChanged("InterestRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanApplicationId {
            get {
                return this.LoanApplicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanApplicationIdField, value) != true)) {
                    this.LoanApplicationIdField = value;
                    this.RaisePropertyChanged("LoanApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanTerm {
            get {
                return this.LoanTermField;
            }
            set {
                if ((this.LoanTermField.Equals(value) != true)) {
                    this.LoanTermField = value;
                    this.RaisePropertyChanged("LoanTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient2City {
            get {
                return this.Recipient2CityField;
            }
            set {
                if ((object.ReferenceEquals(this.Recipient2CityField, value) != true)) {
                    this.Recipient2CityField = value;
                    this.RaisePropertyChanged("Recipient2City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient2Name {
            get {
                return this.Recipient2NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Recipient2NameField, value) != true)) {
                    this.Recipient2NameField = value;
                    this.RaisePropertyChanged("Recipient2Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient2PostCode {
            get {
                return this.Recipient2PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Recipient2PostCodeField, value) != true)) {
                    this.Recipient2PostCodeField = value;
                    this.RaisePropertyChanged("Recipient2PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient2Street {
            get {
                return this.Recipient2StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.Recipient2StreetField, value) != true)) {
                    this.Recipient2StreetField = value;
                    this.RaisePropertyChanged("Recipient2Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient2Town {
            get {
                return this.Recipient2TownField;
            }
            set {
                if ((object.ReferenceEquals(this.Recipient2TownField, value) != true)) {
                    this.Recipient2TownField = value;
                    this.RaisePropertyChanged("Recipient2Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientCity {
            get {
                return this.RecipientCityField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientCityField, value) != true)) {
                    this.RecipientCityField = value;
                    this.RaisePropertyChanged("RecipientCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientName {
            get {
                return this.RecipientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNameField, value) != true)) {
                    this.RecipientNameField = value;
                    this.RaisePropertyChanged("RecipientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientPostCode {
            get {
                return this.RecipientPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientPostCodeField, value) != true)) {
                    this.RecipientPostCodeField = value;
                    this.RaisePropertyChanged("RecipientPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientStreet {
            get {
                return this.RecipientStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientStreetField, value) != true)) {
                    this.RecipientStreetField = value;
                    this.RaisePropertyChanged("RecipientStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientTown {
            get {
                return this.RecipientTownField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientTownField, value) != true)) {
                    this.RecipientTownField = value;
                    this.RaisePropertyChanged("RecipientTown");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanApplicationService.ILoanApplicationService")]
    public interface ILoanApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanApplicationService/GetAllLoanApplications", ReplyAction="http://tempuri.org/ILoanApplicationService/GetAllLoanApplicationsResponse")]
        ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationListResponse GetAllLoanApplications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanApplicationService/GetLoanApplicationById", ReplyAction="http://tempuri.org/ILoanApplicationService/GetLoanApplicationByIdResponse")]
        ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationGetByIdResponse GetLoanApplicationById(ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationGetByIdRequest loanApplicationGetByIdRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanApplicationService/SubmitLoanApplication", ReplyAction="http://tempuri.org/ILoanApplicationService/SubmitLoanApplicationResponse")]
        ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationCreateResponse SubmitLoanApplication(ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationCreateRequest LoanApplicationCreateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanApplicationService/GetOfferLetterForLoanApplicationById", ReplyAction="http://tempuri.org/ILoanApplicationService/GetOfferLetterForLoanApplicationByIdRe" +
            "sponse")]
        ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.OfferLetterGetByIdResponse GetOfferLetterForLoanApplicationById(ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.OfferLetterGetByIdRequest offerLetterGetByIdRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoanApplicationServiceChannel : ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.ILoanApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanApplicationServiceClient : System.ServiceModel.ClientBase<ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.ILoanApplicationService>, ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.ILoanApplicationService {
        
        public LoanApplicationServiceClient() {
        }
        
        public LoanApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationListResponse GetAllLoanApplications() {
            return base.Channel.GetAllLoanApplications();
        }
        
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationGetByIdResponse GetLoanApplicationById(ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationGetByIdRequest loanApplicationGetByIdRequest) {
            return base.Channel.GetLoanApplicationById(loanApplicationGetByIdRequest);
        }
        
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationCreateResponse SubmitLoanApplication(ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.LoanApplicationCreateRequest LoanApplicationCreateRequest) {
            return base.Channel.SubmitLoanApplication(LoanApplicationCreateRequest);
        }
        
        public ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.OfferLetterGetByIdResponse GetOfferLetterForLoanApplicationById(ProEnt.LoanPrequalification.UI.MVC.LoanApplicationService.OfferLetterGetByIdRequest offerLetterGetByIdRequest) {
            return base.Channel.GetOfferLetterForLoanApplicationById(offerLetterGetByIdRequest);
        }
    }
}
